#!/bin/bash
set -x

NAME=${1##*/}
NAME=${NAME%%.*}
NAME="${2}/${NAME}"

if [ ! -d "${NAME}" ]; then
    if [ ! -d "${2}" ]; then
        mkdir "${2}"
    fi	
    cd "${2}"
    git clone "${1}"
    cd "${NAME}"
else
    cd "${NAME}"
    # Get new tags from remote
    git fetch --tags
fi

# Get latest tag name

if [ "${3}" = "-q" ]; then
    latestTag="$(git describe --tags `git rev-list --tags --max-count=1`)"
else
    latestTag=$(git tag | fzf)
fi

# Checkout latest tag
git checkout "${latestTag}"
